version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hpmekong-backend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./uploads:/app/uploads
      - backend_logs:/app/logs
    ports:
      - "8080:8080"
    networks:
      - hpmekong-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hpmekong-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"
    networks:
      - hpmekong-network

networks:
  hpmekong-network:
    driver: bridge

volumes:
  backend_logs:
    driver: local

